### ISSUE TITLE
希望能有MP3导出功能，方便上传到服务器

### ISSUE THREAD

**Issue by zellop** [yxwandroid/flutter_plugin_record#1]
希望能有MP3导出功能，方便上传到服务器

**Comment by yxwandroid** [comment]
@zellop 在回调里面有返回录音地址

**Comment by badboy-tian** [comment]
这里是生成的wav吧, 能生成mp3么

**Comment by yxwandroid** [comment]
@badboy-tian    暂时还不支持mp3

**Comment by badboy-tian** [comment]
@yxwandroid  请问未来有计划支持mp3吗 谢谢

**Comment by yxwandroid** [comment]
@badboy-tian   有计划 但是要一个月之后了  你可以在这个基础上进行二次开发 支持mp3   或则等

**Comment by zellop** [comment]
很好，希望尽快支持Mp3

**Comment by yxwandroid** [comment]
@zellop  要是需要很大的话考虑下周进行开发支持mp3 的功能

**Comment by zellop** [comment]
拜托了，谢谢

**Comment by yxwandroid** [comment]
@zellop 可以关注公众号 获取最新的动态   
![image](https://user-images.githubusercontent.com/9635493/70891191-b91e4600-2021-11ea-970d-a6a5c8fcb174.png)

**Comment by yxwandroid** [comment]
@zellop  @badboy-tian   
android 对 mp3 格式支持不太好 ,可以参考   https://www.jianshu.com/p/9292c2f5aed7  ,可以把录制好的wav转成mp3
