### ISSUE TITLE
请问可以增加录音播放完成的回调之类的吗？

### ISSUE THREAD

**Issue by cn-Meepo** [yxwandroid/flutter_plugin_record#12]
请问可以增加录音播放完成的回调之类的吗？

**Comment by yxwandroid** [comment]
@cn-Meepo  好等下个版本我加上 明天我有时间看看能不能加上

**Comment by cn-Meepo** [comment]
@yxwandroid  谢谢，顺便请问下播放的时候能让声音大一些吗？

**Comment by yxwandroid** [comment]
声音大小的话应该手机音量能控制吧

**Comment by cn-Meepo** [comment]
微信可以选择扬声器或者听筒，播放的时候感觉就像是听筒播放的一样

**Comment by yxwandroid** [comment]
@cn-Meepo   明白了

**Comment by cn-Meepo** [comment]
@yxwandroid 谢谢大佬，辛苦了

**Comment by yxwandroid** [comment]
@cn-Meepo  你微信多少可以加一下微信 做好了通知你  我微信18518318385

**Comment by yxwandroid** [comment]
已解决
