### ISSUE TITLE
长按录音的按钮样式无法更改

### ISSUE THREAD

**Issue by kazeik** [yxwandroid/flutter_plugin_record#16]
想集成这个库，发现按钮样式和设计稿中有出入。查看了下源码，发现已经被写死了。
是否可以修改成动态配置？

**Comment by yxwandroid** [comment]
@kazeik 等有时间我做一下动态配置

**Comment by yxwandroid** [comment]
@你可以Fork 下来  修改发送按钮样式  或则集成之后自己自定义样式
