### ISSUE TITLE
在安卓设备上仿微信录音松开手之后录音没有停止

### ISSUE THREAD

**Issue by pingxiaodou** [yxwandroid/flutter_plugin_record#18]
松开手指后有时候能够停止，有时候停止不了，log还是一直在输出

**Comment by wtus** [comment]
log 不断打印

**Comment by wtus** [comment]
E/FlutterPluginRecordPlugin$MessageRecordListener(17972): MessageRecordListener onVolume 0.3904904782050708
I/flutter (17972): --------FlutterPluginRecord onAmplitude
E/FlutterPluginRecordPlugin$MessageRecordListener(17972): MessageRecordListener

**Comment by yxwandroid** [comment]
已解决
