### ISSUE TITLE
初始化后报错

### ISSUE THREAD

**Issue by kazeik** [yxwandroid/flutter_plugin_record#19]
E/AndroidRuntime(29727): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.thursday.lesbian/com.thursday.lesbian.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property _call has not been initialized
E/AndroidRuntime(29727): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4349)
E/AndroidRuntime(29727): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4392)
E/AndroidRuntime(29727): 	at android.app.ActivityThread.-wrap22(ActivityThread.java)
E/AndroidRuntime(29727): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
E/AndroidRuntime(29727): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(29727): 	at android.os.Looper.loop(Looper.java:156)
E/AndroidRuntime(29727): 	at android.app.ActivityThread.main(ActivityThread.java:6623)
E/AndroidRuntime(29727): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29727): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/AndroidRuntime(29727): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
E/AndroidRuntime(29727): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property _call has not been initialized
E/AndroidRuntime(29727): 	at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.initRecord(FlutterPluginRecordPlugin.kt:68)
E/AndroidRuntime(29727): 	at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.onRequestPermissionsResult(FlutterPluginRecordPlugin.kt:232)
E/AndroidRuntime(29727): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:612)
E/AndroidRuntime(29727): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:356)
E/AndroidRuntime(29727): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:509)
E/AndroidRuntime(29727): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:611)
E/AndroidRuntime(29727): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7340)
E/AndroidRuntime(29727): 	at android.app.Activity.dispatchActivityResult(Activity.java:7192)
E/AndroidRuntime(29727): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4345)
E/AndroidRuntime(29727): 	... 9 more

**Comment by yhz199132** [comment]
你好，这个问题是否已经解决？目前我也遇到同样的问题

**Comment by kazeik** [comment]
@yhz199132  这个问题其实是权限申请回调后的问题，经调试后发现，是未获取到相关权限导致的。
建议你在app启动时，动态申请相关权限。然后就可以解决问题了。

**Comment by yhz199132** [comment]
谢谢，找到问题后，已按相同方式处理了。 379008118 邮箱：379008118@qq.com 签名由 网易邮箱大师 定制 在2020年04月15日 12:42，独行的苏泽 写道： Closed #19. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
