### ISSUE TITLE
ios 不能使用

### ISSUE THREAD

**Issue by Sansuihe** [yxwandroid/flutter_plugin_record#21]
不能使用怎么办

**Comment by yxwandroid** [comment]
@Sansuihe 具体报什么错误

**Comment by Sansuihe** [comment]
> @Sansuihe具体报什么错误
您写的插件ios录音时默认为双声道，刚好我这有个需求双声道的录音却使用不了，想向您了解一下切换单声道录音时候能自己设置值吗

**Comment by yxwandroid** [comment]
![Uploading image.png…]()
默认是单通道  
AVNumberOfChannelsKey：通道数。设成2的话是双声道。iPhone只有一个麦克风，一个单声道的通道足够了，它把你的数据需求削减了一半。

可以参考 
https://www.jianshu.com/p/bd1c8a579224
