### ISSUE TITLE
播放语音功能需求

### ISSUE THREAD

**Issue by ljj-chn** [yxwandroid/flutter_plugin_record#24]
您好！请问可以提供语音播放的通知消息吗，类似您录制时的消息。
比如：成功，失败，完成。播放进度，停止播放，暂停播放。等等
这些都比较常用。

谢谢

**Comment by yxwandroid** [comment]
做这个插件的初衷是为了仿造微信发送语音的功能  你说的这些功能是想把这个插件做成音频播放器么

**Comment by ljj-chn** [comment]
您好，暂时还没有做播放器。我现在是把自己朗读单词的声音录制下来，然后再播放。单词有很多，每个都保存录音，播放时，有时不等前一个播放完，就点击按钮播放下一个，这时就需要主动停掉前一个播放。有时需要连续顺序播放录音，这时就需要前一个录音结束的通知来启动播放下一个。我下面打算录制英语句子，由于播放时间比单词长很多，这时就需要播放进度，以及暂停的功能。
谢谢！

**Comment by ljj-chn** [comment]
您好，我找了另外一个播放语音的插件，暂时可以满足我的要求了。谢谢！
您的录音功能很好用，要是能支持录制aac或mp3就更好了。
