### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by yy1234** [yxwandroid/flutter_plugin_record#25]
1.iOS 录音过短，原生代码报错，应该把异常抛出来
2.RecordResponse里面的msg这个不容易理解，建议用枚举，或者单独添加一个属性来说明，插件回调的状态

**Comment by yxwandroid** [comment]
@yy1234  我可以把你加到项目里面一起维护可以吗

**Comment by yy1234** [comment]
> @yy1234 我可以把你加到项目里面一起维护可以吗

可以的，我这段时间太忙，等我忙完了，一起维护

**Comment by yxwandroid** [comment]
@yy1234 可以加一下联系方式吗

**Comment by yxwandroid** [comment]
已经优化
