### ISSUE TITLE
安卓上申请权限，会出现奔溃的情况

### ISSUE THREAD

**Issue by yy1234** [yxwandroid/flutter_plugin_record#26]
见标题

**Comment by ShengjieGeng** [comment]
借楼，解决了吗

**Comment by yxwandroid** [comment]
奔溃信息有吗
@yy1234 
@ShengjieGeng

**Comment by zhjangbolin** [comment]
应该要加个判断当前是否已经获取录音权限的判断方法，不然安卓上第一次获取完录音权限后，直接就崩溃了

**Comment by yy1234** [comment]
> 应该要加个判断当前是否已经获取录音权限的判断方法，不然安卓上第一次获取完录音权限后，直接就崩溃了

我们另外一台电脑，运行就是正常的，作者的demo运行也是正常的，可不可能是配置的问题呢

**Comment by zhjangbolin** [comment]
> > 应该要加个判断当前是否已经获取录音权限的判断方法，不然安卓上第一次获取完录音权限后，直接就崩溃了
> 
> 我们另外一台电脑，运行就是正常的，作者的demo运行也是正常的，可不可能是配置的问题呢

我们公司电脑第一次运行获取完权限后都会崩溃，判断开启了录音权限后再去做初始化应该可以解决这个问题

**Comment by yy1234** [comment]
> > > 应该要加个判断当前是否已经获取录音权限的判断方法，不然安卓上第一次获取完录音权限后，直接就崩溃了
> > 
> > 
> > 我们另外一台电脑，运行就是正常的，作者的demo运行也是正常的，可不可能是配置的问题呢
> 
> 我们公司电脑第一次运行获取完权限后都会崩溃，判断开启了录音权限后再去做初始化应该可以解决这个问题

好的，谢了

**Comment by ShengjieGeng** [comment]
不让sdk申请权限，自己申请权限再调用、
可以用permission_handler申请权限

**Comment by yy1234** [comment]
> 不让sdk申请权限，自己申请权限再调用、
> 可以用permission_handler申请权限

你们有没有遇到，安卓连续单机2次，后台一直输出日志的情况

**Comment by zhjangbolin** [comment]
不要像demo里面一点击就开始录音，在长按开始的时候再开始录音，不然安卓运行一堆的问题

**Comment by yxwandroid** [comment]
已经解决
