### ISSUE TITLE
这个播放声音 怎么没有用呢

### ISSUE THREAD

**Issue by shoushouxiongying** [yxwandroid/flutter_plugin_record#3]
play是播放什么时候的录音呢 ,如果很多次录音的话 ,怎么播放呢

**Comment by shoushouxiongying** [comment]
播放声音 分成2种,一种是本地的 还有种是远程的

**Comment by shoushouxiongying** [comment]
play的时候 有个状态监听,比如播放中,播放暂停,播放结束

**Comment by shoushouxiongying** [comment]
谢谢

**Comment by yxwandroid** [comment]
> play是播放什么时候的录音呢 ,如果很多次录音的话 ,怎么播放呢
播放的是当前录制完成的声音

**Comment by yxwandroid** [comment]
> 播放声音 分成2种,一种是本地的 还有种是远程的

目前只是提供播放当前播放完成的  播放本地后期会有支持  远程不支持的

**Comment by yxwandroid** [comment]
@shoushouxiongying 
> play的时候 有个状态监听,比如播放中,播放暂停,播放结束
这个插件目的是仿照微信发送语音而作的 目前只提供了播放开始回调 结束回调 别的都没提供
@shoushouxiongying

**Comment by shoushouxiongying** [comment]
好的 我刚才找了个autoplayer插件 先暂时替代一下
