### ISSUE TITLE
解决android 第一次初始化的时候申请权限奔溃问题 这个在0.1.3版本里还没生效是吧？

### ISSUE THREAD

**Issue by yutopipp** [yxwandroid/flutter_plugin_record#30]
引用了版本0.1.3，第一次初始化的时候申请权限时还是奔溃。刚开始写flutter，不太明白，源码更新了，版本没更新，我怎么自己生成一个最新的引用？

**Comment by yutopipp** [comment]
` flutter_plugin_record:
    git:
      url: https://github.com/yxwandroid/flutter_plugin_record.git
      ref: 801c7afea10df580a97912d30c08eafff0c36601`
这样引用
pubspec.lock里是这样：
` flutter_plugin_record:
    dependency: "direct main"
    description:
      path: "."
      ref: "801c7afea10df580a97912d30c08eafff0c36601"
      resolved-ref: "801c7afea10df580a97912d30c08eafff0c36601"
      url: "https://github.com/yxwandroid/flutter_plugin_record.git"
    source: git
    version: "0.1.3"`
运行报错：
`e: C:\Users\Work\AppData\Roaming\Pub\Cache\git\flutter_plugin_record-801c7afea10df580a97912d30c08eafff0c36601\android\src\main\kotlin\record\wilson\flutter\com\flutter_plugin_record\FlutterPluginRecordPlugin.kt: (23, 7): Redeclaration: FlutterPluginRecordPlugin
e: C:\Users\Work\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\flutter_plugin_record-0.1.3\android\src\main\kotlin\record\wilson\flutter\com\flutter_plugin_record\FlutterPluginRecordPlugin.kt: (21, 7): Redeclaration: FlutterPluginRecordPlugin

FAILURE: Build failed with an exception.`

**Comment by yxwandroid** [comment]
@  直接引用master还不行吗

**Comment by yxwandroid** [comment]
@yutopipp

**Comment by yutopipp** [comment]
@yxwandroid  我又试了一下，按你说的第一种引用方式，不写ref,直接引用最新的，就可以了，不崩溃了，谢谢！

**Comment by yxwandroid** [comment]
@yutopipp  我重新提交了一个新的版本 0.1.4  可以引入这个版本

**Comment by yxwandroid** [comment]
@yutopipp https://pub.dev/packages/flutter_plugin_record#-readme-tab-
