### ISSUE TITLE
录制第二个音频，第一个音频被替换

### ISSUE THREAD

**Issue by eyesoffish** [yxwandroid/flutter_plugin_record#32]
您好，我录制了两段音频，第二段会把第一段音频替换掉，因为音频的名字都是保存的时候都是一样的

**Comment by yxwandroid** [comment]
@eyesoffish  是android 还是ios

**Comment by yxwandroid** [comment]
现在提供的有根据传入的路径进行录制  你可以传入指定的路径进行录制

**Comment by yxwandroid** [comment]
![Uploading image.png…]()

**Comment by yxwandroid** [comment]
![image](https://user-images.githubusercontent.com/9635493/82526719-37e65480-9b67-11ea-84a0-4143f07588a8.png)
