### ISSUE TITLE
长按录音申请权限问题

### ISSUE THREAD

**Issue by Zhaojing0987** [yxwandroid/flutter_plugin_record#35]
当长按录音时，会弹出授权框，点击同意后开始录音，但此时长按动作已经结束，不应该开始录音。

**Comment by yxwandroid** [comment]
你可以在你app运行的时候先进行权限的授权,这样不会出现这个问题   或则等我有时间在插件里面修改一下授权逻辑

**Comment by Zhaojing0987** [comment]
我用permission_handler在长按前进行判断，由于permission_handler不区分while in use和always（都返回granted），所以不能正确的判断是否要申请授权

**Comment by yxwandroid** [comment]
你是集成到你的项目里面出现的这个问题还是使用的example 出现的这个问题  我怎么没在example里面复现这个问题

**Comment by yxwandroid** [comment]
@Zhaojing0987

**Comment by yxwandroid** [comment]
没复现 不过我在开始录制的时候添加了一下权限验证操作

**Comment by yxwandroid** [comment]
我发布的了0.1.6版本 你可以试试

**Comment by Zhaojing0987** [comment]
复现步骤：在设置里把example权限改为“使用时询问”。
