### ISSUE TITLE
监听播放音频结束

### ISSUE THREAD

**Issue by Zhaojing0987** [yxwandroid/flutter_plugin_record#37]
在未使用录音功能前，通过playByPath播发音频，音频可以正常播放，但无法监听到播放结束
<img width="886" alt="D4948CA2-9245-4582-AC18-D5D7659DCE6A" src="https://user-images.githubusercontent.com/29828346/84234902-97f96680-ab27-11ea-8a51-5d6da6218afa.png">

**Comment by yxwandroid** [comment]
0.1.17版本已经修复  请更新最新版本

**Comment by yxwandroid** [comment]
@Zhaojing0987

**Comment by Zhaojing0987** [comment]
@yxwandroid 好的，谢谢
