### ISSUE TITLE
引入不了，运行直接闪退

### ISSUE THREAD

**Issue by Luffys6** [yxwandroid/flutter_plugin_record#38]
[        ] Error connecting to the service protocol: failed to connect to http://127.0.0.1:50482/ZQhbdoUolK4=/

**Comment by yxwandroid** [comment]
能具体点吗  是ios 还是android  有日志吗

**Comment by Luffys6** [comment]
Android  有日志，明天回公司我给你截个图，我直接打开Android项目，这个依赖里面的代码都在报错，不知道为啥

**Comment by yxwandroid** [comment]
好   明天我给你解决

**Comment by Luffys6** [comment]
> 好 明天我给你解决

![QQ截图20200616090527](https://user-images.githubusercontent.com/21170493/84721843-32d4c380-afb4-11ea-95dc-dd9097c722b0.png)
![QQ截图20200616093048](https://user-images.githubusercontent.com/21170493/84721845-3405f080-afb4-11ea-9f86-14ee0f5e4a79.png)
第一张是Flutter项目跑的，第二张直接跑的Android项目

**Comment by Luffys6** [comment]
以git方式导入和依赖注入都不行

**Comment by yxwandroid** [comment]
![image](https://user-images.githubusercontent.com/9635493/84722143-f786c480-afb4-11ea-9099-2e465829c7b2.png)
ni
你引入的是我的插件吗  这报错信息 度和插件没关系 
你运行一下example 工程能不能运行

**Comment by Luffys6** [comment]
example可以运行，是你的插件，注释掉就没问题，打开运行直接就闪退了

**Comment by yxwandroid** [comment]
![image](https://user-images.githubusercontent.com/9635493/84722302-6106d300-afb5-11ea-931e-1491b76e3304.png)
这报错信息是这个插件多次注册

**Comment by Luffys6** [comment]
> ![image](https://user-images.githubusercontent.com/9635493/84722302-6106d300-afb5-11ea-931e-1491b76e3304.png)
> 这报错信息是这个插件多次注册

我就是直接引入了啊，然后我项目写有原生交互，是不是因为版本问题，我1.17的

**Comment by yxwandroid** [comment]
> > ![image](https://user-images.githubusercontent.com/9635493/84722302-6106d300-afb5-11ea-931e-1491b76e3304.png)
> > 这报错信息是这个插件多次注册
> 
> 我就是直接引入了啊，然后我项目写有原生交互，是不是因为版本问题，我1.17的

![image](https://user-images.githubusercontent.com/9635493/84722575-2b161e80-afb6-11ea-8ec7-d9be4a0a3f48.png)

你可以新建一个项目然后引入我的插件看看能不能正常使用  若是能正常使用就是你项目里面有问题  
若是不能正常使用的话你在把错误信息给我看一下

**Comment by Luffys6** [comment]
> > > ![image](https://user-images.githubusercontent.com/9635493/84722302-6106d300-afb5-11ea-931e-1491b76e3304.png)
> > > 这报错信息是这个插件多次注册
> > 
> > 
> > 我就是直接引入了啊，然后我项目写有原生交互，是不是因为版本问题，我1.17的
> 
> ![image](https://user-images.githubusercontent.com/9635493/84722575-2b161e80-afb6-11ea-8ec7-d9be4a0a3f48.png)
> 
> 你可以新建一个项目然后引入我的插件看看能不能正常使用 若是能正常使用就是你项目里面有问题
> 若是不能正常使用的话你在把错误信你

> > > ![image](https://user-images.githubusercontent.com/9635493/84722302-6106d300-afb5-11ea-931e-1491b76e3304.png)
> > > 这报错信息是这个插件多次注册
> > 
> > 
> > 我就是直接引入了啊，然后我项目写有原生交互，是不是因为版本问题，我1.17的
> 
> ![image](https://user-images.githubusercontent.com/9635493/84722575-2b161e80-afb6-11ea-8ec7-d9be4a0a3f48.png)
> 
> 你可以新建一个项目然后引入我的插件看看能不能正常使用 若是能正常使用就是你项目里面有问题
> 若是不能正常使用的话你在把错误信息给我看一下

你加我759902931
