### ISSUE TITLE
在使用其他音频播放的时候，在点击录制其他会变得声音非常小

### ISSUE THREAD

**Issue by chaogao** [yxwandroid/flutter_plugin_record#39]
await audioPlayer.setFilePath(path);
audioPlayer.setVolume(10);
audioPlayer.play();

Timer t = Timer(Duration(seconds: 2), () async {
	recordPlugin.start();
});

一进来播放声音正常，2秒后开始录制播放声音就非常小了。产品是希望能有背景录制的音乐。麻烦指教怎么修改呢

**Comment by yxwandroid** [comment]
这个需求太奇怪了吧  把产品打一顿再说
