### ISSUE TITLE
你好, 当录音按钮在TabBarView的某个页面底下的时候无法录音

### ISSUE THREAD

**Issue by badboy-tian** [yxwandroid/flutter_plugin_record#40]
感觉是录音按钮的点击事件和tabbar的左右滑动事件冲突了?
![image](https://user-images.githubusercontent.com/2835129/84899372-2ac37380-b0db-11ea-8331-6cbb35e415e3.png)
这个时候按住没反应

**Comment by yxwandroid** [comment]
@badboy-tian 
https://blog.csdn.net/heming9174/article/details/89921180
https://juejin.im/post/5e9aaac26fb9a03c7762167d
看这两个有没有帮助,
你可以考虑一下 把按住说话放到tabbar 外面    具体情况还是要debug进行分析 
只能帮你到这了
