### ISSUE TITLE
希望能自定义获取权限

### ISSUE THREAD

**Issue by fangshengfy** [yxwandroid/flutter_plugin_record#42]
我看到了之前的版本的issue，但是在app进入的时候就申请本地录音和读写给人的印象会很差，希望能改成可选择的

**Comment by yxwandroid** [comment]
@fangshengfy 等有时间在做优化  或则fork下来进行修改

**Comment by chjsun** [comment]
同求. 而且我不懂Android, 想本地改也没法子

**Comment by fangshengfy** [comment]
现在有一个问题是我在开启app时需要拿到定位的权限，但是现在在第一次打开app只会出现申请录音权限，申请定位选项要第二次打开app才会出现

**Comment by chjsun** [comment]
我是两个权限先后弹出, 录音在前定位在后

**Comment by chjsun** [comment]
我刚刚注释了一行代码,感觉可以, 只是不知道会不会出什么问题, @yxwandroid @fangshengfy 懂的看一下

```
constructor(registrar: Registrar, _channel: MethodChannel) {
        this.registrar = registrar
        this.registrar.addRequestPermissionsResultListener(this)
        this.channel = _channel
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
//            initPermission()
        }
    }
```

**Comment by yxwandroid** [comment]
@chjsun  可以的注释掉这个是可以实现的

**Comment by yxwandroid** [comment]
> 我刚刚注释了一行代码,感觉可以, 只是不知道会不会出什么问题, @yxwandroid @fangshengfy 懂的看一下
> 
> ```
> constructor(registrar: Registrar, _channel: MethodChannel) {
>         this.registrar = registrar
>         this.registrar.addRequestPermissionsResultListener(this)
>         this.channel = _channel
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
> //            initPermission()
>         }
>     }
> ```

@fangshengfy   你可以按照这种方法

**Comment by fangshengfy** [comment]
> > 我刚刚注释了一行代码,感觉可以, 只是不知道会不会出什么问题, @yxwandroid @fangshengfy 懂的看一下
> > ```
> > constructor(registrar: Registrar, _channel: MethodChannel) {
> >         this.registrar = registrar
> >         this.registrar.addRequestPermissionsResultListener(this)
> >         this.channel = _channel
> >         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
> > //            initPermission()
> >         }
> >     }
> > ```
> 
> @fangshengfy 你可以按照这种方法

ios的该怎么修改？

**Comment by chjsun** [comment]
iOS的没遇到这个问题
