### ISSUE TITLE
音频文件以BLOB格式存在sqlite中，如何进行播放？

### ISSUE THREAD

**Issue by kanlidy** [yxwandroid/flutter_plugin_record#47]
RT

startWithPath，好像需要把文件存在一个路径下才能播放，有没有支持BLOB的方案？

**Comment by yxwandroid** [comment]
为什么把音频存入到数据库 为什么不把因为文件存成文件的形式 然后数据库存本地的地址呢   目前不支持blob的模式

**Comment by kanlidy** [comment]
我目前是使用了文件的形式了，用了file_utils保存到另外的目录中了。

音频播放使用startByWavPath，如何在播放的过程中暂停呢？

**Comment by kanlidy** [comment]
是的，我使用file_utils保存到其他的路径下去了~~
