### ISSUE TITLE
关于android的录音权限问题

### ISSUE THREAD

**Issue by lhh-sofy** [yxwandroid/flutter_plugin_record#48]
能否去除android原生代码自带的权限判断...原生的太丑了，样式没有办法定义。
可否痛过别的组件使用，如permission_handler

**Comment by yxwandroid** [comment]
@lhh-sofy    
![image](https://user-images.githubusercontent.com/9635493/88036866-b9ae2a80-cb76-11ea-8a06-fd9649d6e68a.png)
注释掉了 启动就申请权限的代码  你在使用的record插件之前使用permission_handler 进行权限申请

请使用最新版本.0.1.9

**Comment by lhh-sofy** [comment]
好的，非常感谢...

**Comment by yxwandroid** [comment]
@lhh-sofy  你使用新版试试已经发布了
