### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by ShengjieGeng** [yxwandroid/flutter_plugin_record#49]
![image](https://user-images.githubusercontent.com/18364968/88032325-5faa6680-cb70-11ea-9fcf-5f7caa7fc914.png)
![image](https://user-images.githubusercontent.com/18364968/88032422-810b5280-cb70-11ea-9a6d-bdf2829765c3.png)
您好，今天集成的时候调用的startByWavPath报错
请求帮忙，谢谢

**Comment by yxwandroid** [comment]
能否贴一下报错内容

**Comment by yxwandroid** [comment]
@ShengjieGeng 你使用的版本是多少

**Comment by ShengjieGeng** [comment]
![image](https://user-images.githubusercontent.com/18364968/88042056-e44fb180-cb7d-11ea-84f3-2a1fdc2a4137.png)
最新的哦，iOS测试机环境

**Comment by ShengjieGeng** [comment]
> @ShengjieGeng 你使用的版本是多少

最新的 0.1.8

**Comment by yxwandroid** [comment]
@ShengjieGeng 使用0.1.9试试

**Comment by ShengjieGeng** [comment]
> @ShengjieGeng 使用0.1.9试试

还是missing

**Comment by ShengjieGeng** [comment]
![image](https://user-images.githubusercontent.com/18364968/88043342-e581de00-cb7f-11ea-88ee-70dcf7fa32e0.png)
测试环境

**Comment by yxwandroid** [comment]
你运行我的example试试了吗 能不能运行 我是没遇到这个问题

**Comment by ShengjieGeng** [comment]
> 你运行我的example试试了吗 能不能运行 我是没遇到这个问题

调用了flutter clear ，然后卸载app重装了
问题解决了
