### ISSUE TITLE
ios系统录音功能，stop的回调路径一直都是同一个文件

### ISSUE THREAD

**Issue by lanxingye** [yxwandroid/flutter_plugin_record#5]
另外建议回调中加入是否取消发送的标志。

**Comment by yxwandroid** [comment]
@lanxingye  我看你已经修改了ios动态生成路径的相关代码能否 合并到本项目 
可以发送 push request

**Comment by lanxingye** [comment]
是修改了，但有问题，实际录音的文件和返回的文件路径不是同一个。应该是重复调了生成文件名的方法了。导致时间戳变了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wilson"<notifications@github.com&gt;; 
发送时间: 2019年12月26日(星期四) 上午10:44
收件人: "yxwandroid/flutter_plugin_record"<flutter_plugin_record@noreply.github.com&gt;; 
抄送: "郭福海"<634978871@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yxwandroid/flutter_plugin_record] ios系统录音功能，stop的回调路径一直都是同一个文件 (#5)




@lanxingye  我看你已经修改了ios动态生成路径的相关代码能否 合并到本项目
 可以发送 push request
