### ISSUE TITLE
播放语音不能停止吗？

### ISSUE THREAD

**Issue by kanlidy** [yxwandroid/flutter_plugin_record#50]
我看到了相关的issue，作者是不打算支持语音的停止与事件监听吗？

我想加个语音的播放停止与事件，能给个思路吗？

**Comment by yxwandroid** [comment]
@kanlidy  做这个插件的的目的是为了模仿微信发送语音  当初没考虑播放停止功能  不过现在发现还是蛮多人想让加上这个功能 已经有计划做播放停止了  不过要等周日我加上了

**Comment by yxwandroid** [comment]
已经加上
