### ISSUE TITLE
   recordPlugin.dispose(); 会报错日志如下

### ISSUE THREAD

**Issue by lmr520** [yxwandroid/flutter_plugin_record#57]
:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, null, null)
E/flutter (16337): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter (16337): #1      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:166
E/flutter (16337): <asynchronous suspension>
E/flutter (16337): #2      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:339
E/flutter (16337): #3      FlutterPluginRecord._invokeMethod 
package:flutter_plugin_record/flutter_plugin_record.dart:27
E/flutter (16337): #4      FlutterPluginRecord.stopPlay 
package:flutter_plugin_record/flutter_plugin_record.dart:200
E/flutter (16337): #5      FlutterPluginRecord.dispose 
package:flutter_plugin_record/flutter_plugin_record.dart:205
E/flutter (16337): #6      _VoiceWidgetState.dispose 
package:flutter_plugin_record/voice_widget.dart:240
E/flutter (16337): #7      StatefulElement.unmount 
package:flutter/…/widgets/framework.dart:4729
E/flutter (16337): #8      _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1922
E/flutter (16337): #9      _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1920
E/flutter (16337): #10     MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5929
E/flutter (16337): #11     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1918
E/flutter (16337): #12     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1920
E/flutter (16337): #13     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4556
E/flutter (16337): #14     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1918
E/flutter (16337): #15     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1920
E/flutter (16337): #16     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4556
E/flutter (16337): #17     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1918
E/flutter (16337): #18     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1920
E/flutter (16337): #19     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4556
E/flutter (16337): #20     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1918
E/flutter (16337): #21     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1920
E/flutter (16337): #22     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4556
E/flutter (16337): #23     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1918
E/flutter (16337): #24     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1920
E/flutter (16337): #25     MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5929
E/flutter (16337): #26     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1918
E/flutter (16337): #27     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1920
E/flutter (16337): #28     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4556
E/flutter (16337): #29     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1918
E/flutter (16337): #30     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1920
E/flutter (16337): #31     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4556
E/flutter (16337): #32     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1918
E/flutter (16337): #33     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1920
E/flutter (16337): #34     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4556
E/flutter (16337): #35     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1918
E/flutter (16337): #36     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1920
E/flutter (16337): #37     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5817
E/flutter (16337): #38     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1918
E/flutter (16337): #39     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1920
E/flutter (16337): #40     ComponentElement.visitChildren (packag

**Comment by lmr520** [comment]
Failed to handle method call
E/MethodChannel#flutter_plugin_record(20041): kotlin.KotlinNullPointerException
E/MethodChannel#flutter_plugin_record(20041): 	at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.stopPlay(FlutterPluginRecordPlugin.kt:86)
E/MethodChannel#flutter_plugin_record(20041): 	at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.onMethodCall(FlutterPluginRecordPlugin.kt:62)
E/MethodChannel#flutter_plugin_record(20041): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutter_plugin_record(20041): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_plugin_record(20041): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#flutter_plugin_record(20041): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_plugin_record(20041): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/MethodChannel#flutter_plugin_record(20041): 	at android.os.Looper.loop(Looper.java:144)
E/MethodChannel#flutter_plugin_record(20041): 	at android.app.ActivityThread.main(ActivityThread.java:7555)
E/MethodChannel#flutter_plugin_record(20041): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_plugin_record(20041): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
E/MethodChannel#flutter_plugin_record(20041): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
E/flutter (20041): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, null, null)
E/flutter (20041): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter (20041): #1      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:166
E/flutter (20041): <asynchronous suspension>
E/flutter (20041): #2      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:339
E/flutter (20041): #3      FlutterPluginRecord._invokeMethod 
package:flutter_plugin_record/flutter_plugin_record.dart:27
E/flutter (20041): #4      FlutterPluginRecord.stopPlay 
package:flutter_plugin_record/flutter_plugin_record.dart:200
E/flutter (20041): #5      FlutterPluginRecord.dispose 
package:flutter_plugin_record/flutter_plugin_record.dart:205
E/flutter (20041): #6      _SlVoiceWidgetState.dispose 
package:customers/…/msg/chat_voice.dart:238
E/flutter (20041): #7      StatefulElement.unmount 
package:flutter/…/widgets/framework.dart:4729
E/flutter (20041): #8      _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1922
E/flutter (20041): #9      ListIterable.forEach  (dart:_internal/iterable.dart:41:13)
E/flutter (20041): #10     _InactiveElements._unmountAll 
package:flutter/…/widgets/framework.dart:1931
E/flutter (20041): #11     BuildOwner.finalizeTree.<anonymous closure> 
package:flutter/…/widgets/framework.dart:2714
E/flutter (20041): #12     BuildOwner.lockState 
package:flutter/…/widgets/framework.dart:2545
E/flutter (20041): #13     BuildOwner.finalizeTree 
package:flutter/…/widgets/framework.dart:2713
E/flutter (20041): #14     WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:885
E/flutter (20041): #15     RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:284
E/flutter (20041): #16     SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1113
E/flutter (20041): #17     SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1052
E/flutter (20041): #18     SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:968
E/flutter (20041): #19     _rootRun  (dart:async/zone.dart:1184:13)
E/flutter (20041): #20     _CustomZone.run  (dart:async/zone.dart:1077:19)

**Comment by yxwandroid** [comment]
你是不是调用的顺序不对

**Comment by lmr520** [comment]
我看到你的例子微信录音也是会报这个错，如果不主动dispose就不会，但不知道资源有没有被释放

**Comment by yxwandroid** [comment]
好的我看看去

**Comment by yxwandroid** [comment]
已修复

**Comment by lmr520** [comment]
好的
