### ISSUE TITLE
使用录制后，退出页面会调用stopPlay导致异常

### ISSUE THREAD

**Issue by ondev** [yxwandroid/flutter_plugin_record#58]
private fun stopPlay() {
        recorderUtil!!.stopPlay()
    }

这个时候recorderUtil应该是null， 因为没有startPlay。这儿不应该用!!哦, 我觉得应该是?

作者空了修复一下，提交到pub上

**Comment by yxwandroid** [comment]
已经修复  0.2.3 版本
