### ISSUE TITLE
能不能暴露一个参数用来设置刷新的时长（现在插件默认是200ms）

### ISSUE THREAD

**Issue by JsonFu** [yxwandroid/flutter_plugin_record#60]
很荣幸在项目中使用了flutter_plugin_record。我们的app根据后台返回的时间节点，控制朗读mp3中两个时间间隔（时间精确到小数点后两位）的语音。目前设置好两个时间点之后会多读一个单词或少读一个单词。如果方便的话请修改一下代码，方便设置刷新频率，谢谢了。

**Comment by yxwandroid** [comment]
还是没明天你的需求  要不加一下qq吧   1396781292
