### ISSUE TITLE
Android 权限请求问题

### ISSUE THREAD

**Issue by tongyangsheng** [yxwandroid/flutter_plugin_record#64]
第一次使用插件时Log:
W/Activity( 5471): Can request only one set of permissions at a time
E/MethodChannel#flutter_plugin_record( 5471): Failed to handle method call
E/MethodChannel#flutter_plugin_record( 5471): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/MethodChannel#flutter_plugin_record( 5471): 	at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.onRequestPermissionsResult(FlutterPluginRecordPlugin.kt:339)
E/MethodChannel#flutter_plugin_record( 5471): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:664)
E/MethodChannel#flutter_plugin_record( 5471): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:364)
E/MethodChannel#flutter_plugin_record( 5471): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:573)
E/MethodChannel#flutter_plugin_record( 5471): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:602)
E/MethodChannel#flutter_plugin_record( 5471): 	at android.app.Activity.requestPermissions(Activity.java:5236)
E/MethodChannel#flutter_plugin_record( 5471): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:502)
E/MethodChannel#flutter_plugin_record( 5471): 	at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.initPermission(FlutterPluginRecordPlugin.kt:220)
E/MethodChannel#flutter_plugin_record( 5471): 	at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.checkPermission(FlutterPluginRecordPlugin.kt:212)
E/MethodChannel#flutter_plugin_record( 5471): 	at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.init(FlutterPluginRecordPlugin.kt:202)
E/MethodChannel#flutter_plugin_record( 5471): 	at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.onMethodCall(FlutterPluginRecordPlugin.kt:55)
E/MethodChannel#flutter_plugin_record( 5471): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#flutter_plugin_record( 5471): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_plugin_record( 5471): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter_plugin_record( 5471): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_plugin_record( 5471): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/MethodChannel#flutter_plugin_record( 5471): 	at android.os.Looper.loop(Looper.java:176)
E/MethodChannel#flutter_plugin_record( 5471): 	at android.app.ActivityThread.main(ActivityThread.java:8347)
E/MethodChannel#flutter_plugin_record( 5471): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_plugin_record( 5471): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#flutter_plugin_record( 5471): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

看起来是不允许同时请求多个权限

**Comment by yxwandroid** [comment]
你使用的手机android 版本是多少

**Comment by tongyangsheng** [comment]
android 9.0 在项目example 的那个仿微信聊天界面，第一次进入时权限授权完毕后 不会初始化插件，第二次进入初始化正常。

**Comment by tongyangsheng** [comment]
repaired~ 
![image](https://user-images.githubusercontent.com/32046282/91375518-82a1f780-e84d-11ea-9895-d668d5798468.png)
权限获取完之后少了initRecord()，下个版本可以加一下，我这边自己改源码了 😄，closed

**Comment by yxwandroid** [comment]
好我我现在加上更新一个版本

**Comment by yxwandroid** [comment]
请使用0.2.5版本
