### ISSUE TITLE
iOS stopPlay功能 异常

### ISSUE THREAD

**Issue by YubiwaStar** [yxwandroid/flutter_plugin_record#66]
使用的平台 ios
使用的版本 0.2.5
问题描述 调用stopPlay 方法无效，语音继续播放，结束后也无法收到播放状态回调。

**Comment by yxwandroid** [comment]
你试试example 能不能复现这个问题

**Comment by YubiwaStar** [comment]
用暂停播放Api 实现了功能。谢谢
