### ISSUE TITLE
Can't upgrade to flutter 2.0

### ISSUE THREAD

**Issue by cavanlee** [yxwandroid/flutter_plugin_record#76]
Because every version of flutter_plugin_record from git depends on uuid ^2.2.3 which doesn't match any versions, flutter_plugin_record from git is forbidden.
So, because fans_learning_app depends on flutter_plugin_record from git, version solving failed.

**Comment by ondev** [comment]
not support null safe

**Comment by yxwandroid** [comment]
已经支持flutter 2.0 了
